// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "BlueprintExportTypes.generated.h"

/** Current schema version for exports */
#define BLUEPRINT_EXPORT_SCHEMA_VERSION TEXT("1.0.0")

/** Exit codes for commandlet operations */
namespace EBlueprintExportExitCode
{
	constexpr int32 Success = 0;
	constexpr int32 ValidationFailed = 1;
	constexpr int32 RuntimeError = 2;
}

/**
 * Blueprint type enumeration
 */
UENUM()
enum class EBlueprintExportType : uint8
{
	Normal,
	Const,
	MacroLibrary,
	Interface,
	LevelScript,
	FunctionLibrary,
	Unknown
};

/**
 * Pin direction
 */
UENUM()
enum class EExportPinDirection : uint8
{
	Input,
	Output
};

/**
 * Dependency type
 */
UENUM()
enum class EExportDependencyType : uint8
{
	Hard,
	Soft
};

/**
 * Diff change type
 */
UENUM()
enum class EBlueprintDiffChangeType : uint8
{
	Added,
	Removed,
	Modified,
	Moved,
	TypeChanged,
	ConnectionChanged
};

/**
 * Export configuration options
 */
USTRUCT(BlueprintType)
struct BLUEPRINTEXPORTER_API FBlueprintExportConfig
{
	GENERATED_BODY()

	/** Output directory for exported files */
	UPROPERTY(EditAnywhere, Category = "Export")
	FString OutputDirectory;

	/** Include Blueprint dependencies */
	UPROPERTY(EditAnywhere, Category = "Export")
	bool bIncludeDependencies = false;

	/** Maximum dependency depth (0 = unlimited) */
	UPROPERTY(EditAnywhere, Category = "Export", meta = (EditCondition = "bIncludeDependencies", ClampMin = "0", ClampMax = "10"))
	int32 DependencyDepth = 1;

	/** Export human-readable text summary */
	UPROPERTY(EditAnywhere, Category = "Export")
	bool bExportHumanReadable = true;

	/** Export digest/metrics JSON */
	UPROPERTY(EditAnywhere, Category = "Export")
	bool bExportDigest = true;

	/** Pretty print JSON output */
	UPROPERTY(EditAnywhere, Category = "Format")
	bool bPrettyPrint = true;

	/** Also export State Tree assets found in the search paths */
	UPROPERTY(EditAnywhere, Category = "Export")
	bool bExportStateTrees = false;
};

/**
 * Pin type information for serialization
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedPinType
{
	GENERATED_BODY()

	UPROPERTY()
	FString Category;

	UPROPERTY()
	FString SubCategoryObject;

	UPROPERTY()
	FString PinSubCategory;

	UPROPERTY()
	bool bIsArray = false;

	UPROPERTY()
	bool bIsSet = false;

	UPROPERTY()
	bool bIsMap = false;

	UPROPERTY()
	bool bIsReference = false;

	UPROPERTY()
	bool bIsConst = false;

	UPROPERTY()
	bool bIsWeakPointer = false;

	UPROPERTY()
	FString ValueTerminalType;

	/** True if this pin type has a broken/orphaned object reference */
	UPROPERTY()
	bool bHasBrokenReference = false;

	/** Description of what reference is broken (e.g., deleted class, missing asset) */
	UPROPERTY()
	FString BrokenReferenceInfo;

	/** True if SubCategoryObject was resolved from a trustworthy source (property reflection or node context).
	 *  False if the serializer left SubCategoryObject blank because the PinSubCategoryObject weak pointer
	 *  was not safe to access and no fallback was available. Lets AI consumers distinguish "no subtype"
	 *  from "subtype unknown". Defaults to true so older JSON (where this field is absent) is treated
	 *  as resolved — only the defensive-blanking path sets this to false. */
	UPROPERTY()
	bool bSubCategoryObjectResolved = true;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedPinType FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Pin connection reference
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedPinConnection
{
	GENERATED_BODY()

	UPROPERTY()
	FString NodeId;

	UPROPERTY()
	FString PinId;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedPinConnection FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Exported pin data
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedPin
{
	GENERATED_BODY()

	UPROPERTY()
	FString PinId;

	UPROPERTY()
	FString PinName;

	UPROPERTY()
	FString PinFriendlyName;

	UPROPERTY()
	EExportPinDirection Direction = EExportPinDirection::Input;

	UPROPERTY()
	FExportedPinType PinType;

	UPROPERTY()
	FString DefaultValue;

	UPROPERTY()
	FString AutogeneratedDefaultValue;

	UPROPERTY()
	bool bHidden = false;

	UPROPERTY()
	bool bNotConnectable = false;

	UPROPERTY()
	bool bAdvancedView = false;

	UPROPERTY()
	TArray<FExportedPinConnection> Connections;

	/** True if this pin has an error (orphaned node, invalid state, etc.) */
	UPROPERTY()
	bool bHasError = false;

	/** Error message describing what's wrong with this pin */
	UPROPERTY()
	FString ErrorMessage;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedPin FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Exported node data
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedNode
{
	GENERATED_BODY()

	UPROPERTY()
	FString NodeId;

	UPROPERTY()
	FString NodeGuid;

	UPROPERTY()
	FString NodeClass;

	UPROPERTY()
	FString NodeTitle;

	UPROPERTY()
	FString NodeType;

	UPROPERTY()
	int32 PositionX = 0;

	UPROPERTY()
	int32 PositionY = 0;

	UPROPERTY()
	FString Comment;

	UPROPERTY()
	bool bCommentBubbleVisible = false;

	UPROPERTY()
	bool bCommentBubblePinned = false;

	UPROPERTY()
	FString NodeColor;

	UPROPERTY()
	TArray<FExportedPin> Pins;

	/** Node-specific data stored as JSON string for extensibility */
	UPROPERTY()
	FString NodeSpecificData;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedNode FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Exported graph data
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedGraph
{
	GENERATED_BODY()

	UPROPERTY()
	FString GraphName;

	UPROPERTY()
	FString GraphGuid;

	UPROPERTY()
	FString GraphType;

	UPROPERTY()
	FString SchemaClass;

	UPROPERTY()
	TArray<FExportedNode> Nodes;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedGraph FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Variable flags
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedVariableFlags
{
	GENERATED_BODY()

	UPROPERTY()
	bool bInstanceEditable = false;

	UPROPERTY()
	bool bBlueprintReadOnly = false;

	UPROPERTY()
	bool bExposeOnSpawn = false;

	UPROPERTY()
	bool bPrivate = false;

	UPROPERTY()
	bool bExposeToCinematics = false;

	UPROPERTY()
	bool bReplicated = false;

	UPROPERTY()
	FString ReplicationCondition;

	/** CPF_RepNotify: variable triggers an OnRep_<Name> callback on replication. */
	UPROPERTY()
	bool bRepNotify = false;

	/** Name of the OnRep function when bRepNotify is true; empty string otherwise. */
	UPROPERTY()
	FString RepNotifyFunc;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedVariableFlags FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Exported variable data
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedVariable
{
	GENERATED_BODY()

	UPROPERTY()
	FString VariableName;

	UPROPERTY()
	FString VariableGuid;

	UPROPERTY()
	FExportedPinType VariableType;

	UPROPERTY()
	FString DefaultValue;

	UPROPERTY()
	FString Category;

	UPROPERTY()
	FExportedVariableFlags Flags;

	UPROPERTY()
	FString ToolTip;

	UPROPERTY()
	TMap<FString, FString> MetaData;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedVariable FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Function parameter data
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedFunctionParam
{
	GENERATED_BODY()

	UPROPERTY()
	FString ParamName;

	UPROPERTY()
	FExportedPinType ParamType;

	UPROPERTY()
	FString DefaultValue;

	UPROPERTY()
	bool bIsOutput = false;

	UPROPERTY()
	bool bPassByReference = false;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedFunctionParam FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Function flags
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedFunctionFlags
{
	GENERATED_BODY()

	UPROPERTY()
	bool bPure = false;

	UPROPERTY()
	bool bConst = false;

	UPROPERTY()
	bool bStatic = false;

	UPROPERTY()
	bool bCallInEditor = false;

	UPROPERTY()
	bool bOverride = false;

	UPROPERTY()
	bool bEvent = false;

	UPROPERTY()
	FString AccessSpecifier;

	/** RPC net-exec flags (set from UK2Node_FunctionEntry::GetFunctionFlags()). */
	UPROPERTY()
	bool bServer = false;

	UPROPERTY()
	bool bClient = false;

	UPROPERTY()
	bool bNetMulticast = false;

	UPROPERTY()
	bool bReliable = false;

	UPROPERTY()
	bool bBlueprintAuthorityOnly = false;

	UPROPERTY()
	bool bBlueprintCosmetic = false;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedFunctionFlags FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Exported function data
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedFunction
{
	GENERATED_BODY()

	UPROPERTY()
	FString FunctionName;

	UPROPERTY()
	FString FunctionGuid;

	UPROPERTY()
	FExportedFunctionFlags Flags;

	UPROPERTY()
	TArray<FExportedFunctionParam> Inputs;

	UPROPERTY()
	TArray<FExportedFunctionParam> Outputs;

	UPROPERTY()
	TArray<FExportedVariable> LocalVariables;

	UPROPERTY()
	FString Description;

	UPROPERTY()
	TArray<FString> Keywords;

	UPROPERTY()
	FString Category;

	UPROPERTY()
	FExportedGraph Graph;

	/** True iff this function is an override of an interface function —
	 *  i.e. the UEdGraph* lives on `Blueprint->ImplementedInterfaces[].Graphs`
	 *  rather than `Blueprint->FunctionGraphs`. Surfaces interface-stub
	 *  overrides that `implement_interface_function` detects but the old
	 *  exporter missed (the "invisible stub" bug closed in M26.1.1). */
	UPROPERTY()
	bool bIsInterfaceOverride = false;

	/** When `bIsInterfaceOverride` is true, the `/Game/...` class path of
	 *  the interface Blueprint this override belongs to (the one listed on
	 *  `Blueprint->ImplementedInterfaces`). Empty otherwise. */
	UPROPERTY()
	FString InterfaceClassPath;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedFunction FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Component property
 *
 * For ordinary properties, `Value` carries the flat `ExportTextItem_Direct` string and
 * `bIsInstancedSubobject` is false.
 *
 * For Instanced / EditInlineNew subobject references (e.g. `UAIPerceptionComponent::SenseConfigs`,
 * GAS `AbilitySystemComponent` attribute sets, anim instance layers), the serializer
 * additionally populates `SubobjectJsonValues` with a structured JSON description of each
 * referenced subobject so AI consumers can read nested property values (sight radius,
 * hearing range, affiliation, etc.) instead of parsing the opaque `Value` blob.
 *
 * Each element of `SubobjectJsonValues` is an FJsonObject with shape:
 *   { "classPath": "/Script/AIModule.AISenseConfig_Sight",
 *     "objectName": "AISenseConfig_Sight_0",
 *     "arrayIndex": 0,             // optional, present for array/map contexts
 *     "mapKey": "...",             // optional, present for map contexts
 *     "properties": [ { "propertyName", "propertyType", "value",
 *                       "bIsInstancedSubobject"?, "subobjects"? } ],
 *     "bTruncated": true,          // optional, emitted only when true
 *     "bCycleDetected": true,      // optional, emitted only when true
 *     "bHasBrokenReference": true, // optional, emitted only when true
 *     "brokenReferenceInfo": "..." // optional
 *   }
 *
 * `SubobjectJsonValues` is NOT a UPROPERTY: the nested "properties" array inside each
 * subobject is itself an array of FExportedComponentProperty-shaped JSON, which would
 * create an A->B->A USTRUCT cycle that UHT does not support. The tree is emitted and
 * parsed as opaque JSON by `ToJson`/`FromJson`; no typed C++ consumer needs to walk it.
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedComponentProperty
{
	GENERATED_BODY()

	UPROPERTY()
	FString PropertyName;

	UPROPERTY()
	FString PropertyType;

	UPROPERTY()
	FString Value;

	/** True when this property points to one or more Instanced / EditInlineNew subobjects
	 *  and `SubobjectJsonValues` has been populated with their structured property trees. */
	UPROPERTY()
	bool bIsInstancedSubobject = false;

	/** Structured description of each instanced subobject this property references.
	 *  Empty for non-instanced properties. See struct doc comment for JSON shape. */
	TArray<TSharedPtr<FJsonValue>> SubobjectJsonValues;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedComponentProperty FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Exported component data (for Actor blueprints)
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedComponent
{
	GENERATED_BODY()

	UPROPERTY()
	FString ComponentName;

	UPROPERTY()
	FString ComponentClass;

	UPROPERTY()
	FString ParentComponentName;

	UPROPERTY()
	bool bIsRootComponent = false;

	UPROPERTY()
	FString AttachSocketName;

	UPROPERTY()
	TArray<FExportedComponentProperty> Properties;

	// Note: Not using UPROPERTY - UE reflection doesn't support recursive structs via arrays
	// Serialization is handled manually via ToJson/FromJson
	TArray<FExportedComponent> ChildComponents;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedComponent FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Blueprint dependency reference
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedDependency
{
	GENERATED_BODY()

	UPROPERTY()
	FString AssetPath;

	UPROPERTY()
	FString AssetName;

	UPROPERTY()
	EExportDependencyType DependencyType = EExportDependencyType::Hard;

	UPROPERTY()
	bool bIsBlueprint = false;

	UPROPERTY()
	bool bIsNativeClass = false;

	UPROPERTY()
	FString Description;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedDependency FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Parent class information
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedParentClass
{
	GENERATED_BODY()

	UPROPERTY()
	FString ClassName;

	UPROPERTY()
	FString ClassPath;

	UPROPERTY()
	bool bIsNative = false;

	UPROPERTY()
	FString ModuleName;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedParentClass FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Export metadata/info
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportInfo
{
	GENERATED_BODY()

	UPROPERTY()
	FString SchemaVersion;

	UPROPERTY()
	FString EngineVersion;

	UPROPERTY()
	FString PluginVersion;

	UPROPERTY()
	FString ExportTimestamp;

	UPROPERTY()
	FString ContentHash;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportInfo FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

// Forward declaration for recursive FExportedAnimState -> FExportedStateMachine dependency
struct FExportedStateMachine;

/**
 * Transition blend settings for AnimBP state machine transitions
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedTransitionBlendSettings
{
	GENERATED_BODY()

	/** Crossfade duration in seconds */
	UPROPERTY()
	float CrossfadeDuration = 0.0f;

	/** Blend mode (EAlphaBlendOption as string, e.g., "Linear", "Cubic", "HermiteCubic") */
	UPROPERTY()
	FString BlendMode;

	/** Crossfade mode (ETransitionBlendMode as string, e.g., "BlendDuration", "Proportional") */
	UPROPERTY()
	FString CrossfadeMode;

	/** Logic type (ETransitionLogicType as string, e.g., "StandardBlend", "Inertialization", "Custom") */
	UPROPERTY()
	FString LogicType;

	/** Priority order for multiple transitions from same state */
	UPROPERTY()
	int32 PriorityOrder = 0;

	/** Whether transition uses automatic rule based on sequence player */
	UPROPERTY()
	bool bAutomaticRuleBasedOnSequencePlayer = false;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedTransitionBlendSettings FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Exported animation state within an AnimBP state machine
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedAnimState
{
	GENERATED_BODY()

	UPROPERTY()
	FString StateName;

	UPROPERTY()
	FString StateGuid;

	/** State type: "State", "Conduit", or "Entry" */
	UPROPERTY()
	FString StateType;

	UPROPERTY()
	FExportedGraph AnimGraph;

	// Note: Not using UPROPERTY - UE reflection doesn't support recursive structs via arrays
	// FExportedStateMachine contains FExportedAnimState which contains FExportedStateMachine
	// Serialization is handled manually via ToJson/FromJson
	TArray<FExportedStateMachine> NestedStateMachines;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedAnimState FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Exported animation transition within an AnimBP state machine
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedAnimTransition
{
	GENERATED_BODY()

	UPROPERTY()
	FString TransitionName;

	UPROPERTY()
	FString TransitionGuid;

	UPROPERTY()
	FString SourceState;

	UPROPERTY()
	FString TargetState;

	UPROPERTY()
	FExportedGraph RuleGraph;

	UPROPERTY()
	FExportedTransitionBlendSettings BlendSettings;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedAnimTransition FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Exported AnimBP state machine (contains states and transitions)
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedStateMachine
{
	GENERATED_BODY()

	UPROPERTY()
	FString MachineName;

	UPROPERTY()
	FString MachineGuid;

	// Note: Not using UPROPERTY - FExportedAnimState contains non-UPROPERTY recursive NestedStateMachines
	// Serialization is handled manually via ToJson/FromJson
	TArray<FExportedAnimState> States;

	// Note: Not using UPROPERTY - manual serialization for consistency with States array
	TArray<FExportedAnimTransition> Transitions;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedStateMachine FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Exported UMG widget tree node.
 *
 * Captures a single node in a WidgetBlueprint's widget hierarchy — the
 * root UWidget of `UBaseWidgetBlueprint::WidgetTree` and each recursive
 * descendant via `UPanelWidget::GetChildAt`. Authored child order is
 * preserved (slot order is semantically load-bearing in UMG layout).
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedWidgetNode
{
	GENERATED_BODY()

	/** Widget's UObject name (matches the variable name when promoted). */
	UPROPERTY()
	FString WidgetName;

	/** Full class path of the UWidget subclass (e.g., "/Script/UMG.HorizontalBox"). */
	UPROPERTY()
	FString WidgetClass;

	/** True when the widget is exposed as a Blueprint variable (bIsVariable / BindWidget). */
	UPROPERTY()
	bool bIsVariable = false;

	/** Slot struct class path (e.g., "/Script/UMG.HorizontalBoxSlot"). Empty for the root. */
	UPROPERTY()
	FString SlotClass;

	// Recursive children — non-UPROPERTY since UE reflection doesn't
	// support TArray<FStruct> where FStruct contains itself. Manual
	// ToJson/FromJson carries them. Same pattern as FExportedAnimState::NestedStateMachines.
	TArray<FExportedWidgetNode> Children;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedWidgetNode FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Complete exported Blueprint data
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportedBlueprint
{
	GENERATED_BODY()

	UPROPERTY()
	FExportInfo ExportInfo;

	UPROPERTY()
	FString AssetPath;

	UPROPERTY()
	FString AssetName;

	UPROPERTY()
	FString BlueprintGuid;

	UPROPERTY()
	EBlueprintExportType BlueprintType = EBlueprintExportType::Normal;

	/** Native UObject subclass name (e.g., "AnimBlueprint", "WidgetBlueprint", "Blueprint").
	 *  Detected via UE reflection, always populated, never empty. */
	UPROPERTY()
	FString BlueprintSubclass;

	UPROPERTY()
	FExportedParentClass ParentClass;

	UPROPERTY()
	TArray<FString> ImplementedInterfaces;

	UPROPERTY()
	TArray<FExportedVariable> Variables;

	UPROPERTY()
	TArray<FExportedFunction> Functions;

	UPROPERTY()
	TArray<FExportedFunction> Macros;

	UPROPERTY()
	FExportedGraph EventGraph;

	UPROPERTY()
	FExportedGraph ConstructionScript;

	UPROPERTY()
	TArray<FExportedComponent> Components;

	/** Class Default Object properties — authored Details-panel values on the generated
	 *  class's CDO that aren't captured by Variables (which serializes the declared
	 *  fields) or Components (SCS hierarchy). Populated only for properties inherited
	 *  from the parent class chain and diffed against the parent CDO, so entries are
	 *  strictly authored overrides on top of parent defaults.
	 *
	 *  Critical for data-carrier Blueprints: `GameplayEffect` subclasses store their
	 *  `Modifiers` / `DurationPolicy` / GameplayCue list here; `GameplayAbility` subclasses
	 *  store `AbilityTags` / `CostGameplayEffectClass`; `DataAsset` subclasses store the
	 *  authored payload properties. Regular BPs use this for Actor-level overrides like
	 *  `bReplicates` / `NetUpdateFrequency` that live on the CDO.
	 *
	 *  Instanced / EditInlineNew subobject fields (e.g. GE modifier components,
	 *  AbilitySystemComponent attribute sets) surface through the same M9
	 *  `bIsInstancedSubobject` + `SubobjectJsonValues` recursive tree the component
	 *  walker uses. */
	UPROPERTY()
	TArray<FExportedComponentProperty> CDOProperties;

	/** Data-carrier kind discriminator — `GameplayEffect` / `GameplayAbility` / `DataAsset`
	 *  when `GeneratedClass->IsChildOf` the corresponding base; empty otherwise. Computed
	 *  at serialize time because `FExportedBlueprint` consumers (inventory commandlet,
	 *  HEALTH_REPORT) don't carry live UClass handles. Used to emit specialized-section
	 *  applicable markers (`GameplayEffect.CDO` etc.) so HEALTH_REPORT can flag a
	 *  data-carrier BP whose CDO walk produced no authored overrides. */
	UPROPERTY()
	FString DataCarrierKind;

	UPROPERTY()
	TArray<FExportedGraph> AdditionalGraphs;

	// Note: Not using UPROPERTY - contains recursive types via FExportedAnimState::NestedStateMachines
	// Serialization is handled manually via ToJson/FromJson
	TArray<FExportedStateMachine> StateMachines;

	// WidgetBlueprint tree — root node at index 0, or empty for non-Widget BPs.
	// Non-UPROPERTY because FExportedWidgetNode contains recursive Children.
	// Serialization is handled manually via ToJson/FromJson.
	TArray<FExportedWidgetNode> WidgetTree;

	UPROPERTY()
	TArray<FExportedDependency> Dependencies;

	UPROPERTY()
	TMap<FString, FString> MetaData;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportedBlueprint FromJson(const TSharedPtr<FJsonObject>& JsonObject);

	/** Compute content hash for change detection */
	FString ComputeContentHash() const;
};

/**
 * Manifest entry for a single exported Blueprint
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportManifestEntry
{
	GENERATED_BODY()

	UPROPERTY()
	FString AssetPath;

	UPROPERTY()
	FString AssetName;

	UPROPERTY()
	FString ExportFileName;

	UPROPERTY()
	FString ContentHash;

	/** Asset type discriminator: "Blueprint" or "StateTree" */
	UPROPERTY()
	FString AssetType;

	/** Native Blueprint subclass for filtering (e.g., "AnimBlueprint"). Empty for non-Blueprint assets. */
	UPROPERTY()
	FString BlueprintSubclass;

	UPROPERTY()
	int32 NodeCount = 0;

	UPROPERTY()
	int32 FunctionCount = 0;

	UPROPERTY()
	float ComplexityScore = 0.0f;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportManifestEntry FromJson(const TSharedPtr<FJsonObject>& JsonObject);
};

/**
 * Export manifest containing all exported Blueprints
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FExportManifest
{
	GENERATED_BODY()

	UPROPERTY()
	FString SchemaVersion;

	UPROPERTY()
	FString EngineVersion;

	UPROPERTY()
	FString PluginVersion;

	UPROPERTY()
	FString ExportTimestamp;

	UPROPERTY()
	TArray<FExportManifestEntry> Entries;

	UPROPERTY()
	TMap<FString, FString> ExportConfig;

	TSharedPtr<FJsonObject> ToJson() const;
	static FExportManifest FromJson(const TSharedPtr<FJsonObject>& JsonObject);

	bool SaveToFile(const FString& FilePath) const;
	static bool LoadFromFile(const FString& FilePath, FExportManifest& OutManifest);
};

/**
 * Diff change entry
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FBlueprintDiffChange
{
	GENERATED_BODY()

	UPROPERTY()
	EBlueprintDiffChangeType ChangeType = EBlueprintDiffChangeType::Modified;

	UPROPERTY()
	FString Category;

	UPROPERTY()
	FString ElementPath;

	UPROPERTY()
	FString ElementName;

	UPROPERTY()
	FString OldValue;

	UPROPERTY()
	FString NewValue;

	UPROPERTY()
	FString Description;

	TSharedPtr<FJsonObject> ToJson() const;
};

/**
 * Complete diff result between two Blueprints
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FBlueprintDiffResult
{
	GENERATED_BODY()

	UPROPERTY()
	FString SourcePath;

	UPROPERTY()
	FString TargetPath;

	UPROPERTY()
	bool bHasChanges = false;

	UPROPERTY()
	int32 NodesAdded = 0;

	UPROPERTY()
	int32 NodesRemoved = 0;

	UPROPERTY()
	int32 NodesModified = 0;

	UPROPERTY()
	int32 ConnectionsChanged = 0;

	UPROPERTY()
	int32 VariablesChanged = 0;

	UPROPERTY()
	int32 FunctionsChanged = 0;

	UPROPERTY()
	int32 LayoutChanges = 0;

	UPROPERTY()
	TArray<FBlueprintDiffChange> Changes;

	TSharedPtr<FJsonObject> ToJson() const;

	FString GetSummary() const;
	bool SaveToFile(const FString& FilePath) const;
};

/**
 * Export metrics for CI reporting
 */
USTRUCT()
struct BLUEPRINTEXPORTER_API FBlueprintExportMetrics
{
	GENERATED_BODY()

	UPROPERTY()
	FString Timestamp;

	UPROPERTY()
	int32 TotalBlueprints = 0;

	UPROPERTY()
	int32 SuccessCount = 0;

	UPROPERTY()
	int32 FailureCount = 0;

	UPROPERTY()
	float TotalExportTimeSeconds = 0.0f;

	UPROPERTY()
	TArray<FString> FailedAssets;

	UPROPERTY()
	TMap<FString, float> PerBlueprintMetrics;

	TSharedPtr<FJsonObject> ToJson() const;
	bool SaveToFile(const FString& FilePath) const;
};
