// Copyright 10 Chambers. All Rights Reserved.

#include "TextExport/EnvQueryDeepRenderer.h"
#include "TextExport/DeepDumpRenderer.h"
#include "TextExport/DeepRenderShared.h"

#include "UObject/Object.h"
#include "UObject/UnrealType.h"
#include "UObject/Class.h"

#include "EnvironmentQuery/EnvQuery.h"
#include "EnvironmentQuery/EnvQueryOption.h"
#include "EnvironmentQuery/EnvQueryGenerator.h"
#include "EnvironmentQuery/EnvQueryTest.h"

namespace
{
	using BlueprintExporter::DeepRender::EscTbl;
	using BlueprintExporter::DeepRender::RenderUObjectPropertiesTable;

	FString DoRenderEnvQuery(UEnvQuery* EQS)
	{
		FString Md;
		Md.Reserve(8 * 1024);

		Md += FString::Printf(TEXT("# %s — Deep Dump (Tier 2)\n\n"), *EQS->GetName());
		Md += TEXT("> Generated by `DeepDump` for an EnvQuery asset. Adds full UPROPERTY tables for every option's generator and every test in the query — Tier 1 records shape (option names, generator class, ordered test class list) but not the authored values like `Radius` on a `EnvQueryGenerator_SimpleGrid`, `TestPurpose` on a test, `ScoringEquation` / `ClampMin` / `Weight`, or the actual gameplay-tag / trace / distance parameters driving each test. This is the Tier 2 complement.\n\n");

		// ---- Identity ----
		Md += TEXT("## Identity\n\n");
		Md += TEXT("| Field | Value |\n|---|---|\n");
		Md += FString::Printf(TEXT("| Asset path | `%s` |\n"), *EscTbl(EQS->GetPathName()));
		Md += FString::Printf(TEXT("| Asset name | `%s` |\n"), *EscTbl(EQS->GetName()));
		Md += TEXT("| Asset type | `EnvQuery` |\n");
		UClass* Cls = EQS->GetClass();
		UClass* ParentCls = Cls ? Cls->GetSuperClass() : nullptr;
		if (ParentCls)
		{
			Md += FString::Printf(TEXT("| Parent class | `%s` |\n"), *EscTbl(ParentCls->GetPathName()));
		}

		const TArray<UEnvQueryOption*>& Options = EQS->GetOptions();
		int32 TotalTests = 0;
		for (const UEnvQueryOption* Opt : Options)
		{
			if (Opt)
			{
				TotalTests += Opt->Tests.Num();
			}
		}
		Md += FString::Printf(TEXT("| Options | **%d** |\n"), Options.Num());
		Md += FString::Printf(TEXT("| Tests (total) | **%d** |\n"), TotalTests);
		Md += TEXT("\n");

		// ---- Options ----
		// Authored order is load-bearing (brief §8 — query options evaluate in
		// declaration order and the first passing option wins), so don't sort.
		if (Options.Num() == 0)
		{
			Md += TEXT("## Options\n\n_No options — query has no generators configured._\n\n");
			return Md;
		}

		Md += FString::Printf(TEXT("## Options (%d, %d tests total)\n\n"), Options.Num(), TotalTests);

		for (int32 OptIdx = 0; OptIdx < Options.Num(); ++OptIdx)
		{
			const UEnvQueryOption* Opt = Options[OptIdx];
			if (!Opt)
			{
				Md += FString::Printf(TEXT("### Option %d — _(null option)_\n\n"), OptIdx);
				continue;
			}

			const UEnvQueryGenerator* Gen = Opt->Generator;
			const FString OptionName = Gen
				? (Gen->OptionName.IsEmpty() ? Gen->GetName() : Gen->OptionName)
				: FString(TEXT("(no generator)"));

			Md += FString::Printf(TEXT("### Option %d — `%s`\n\n"), OptIdx, *EscTbl(OptionName));

			// Generator block.
			if (Gen)
			{
				Md += FString::Printf(TEXT("#### Generator — `%s`\n\n"), *EscTbl(Gen->GetClass()->GetName()));
				Md += FString::Printf(TEXT("- Class: `%s`\n\n"), *EscTbl(Gen->GetClass()->GetPathName()));
				const int32 N = RenderUObjectPropertiesTable(Md, Gen);
				if (N == 0)
				{
					Md += TEXT("_(generator declares no exposed UPROPERTYs)_\n\n");
				}
			}
			else
			{
				Md += TEXT("#### Generator — _(unset)_\n\n");
				Md += TEXT("_No generator assigned — this option will produce no items at runtime._\n\n");
			}

			// Tests block.
			if (Opt->Tests.Num() == 0)
			{
				Md += TEXT("#### Tests\n\n_No tests — items pass through unfiltered and unscored._\n\n");
				continue;
			}

			Md += FString::Printf(TEXT("#### Tests (%d)\n\n"), Opt->Tests.Num());
			for (int32 TestIdx = 0; TestIdx < Opt->Tests.Num(); ++TestIdx)
			{
				const UEnvQueryTest* Test = Opt->Tests[TestIdx].Get();
				if (!Test)
				{
					Md += FString::Printf(TEXT("##### Test %d — _(null test)_\n\n"), TestIdx);
					continue;
				}
				Md += FString::Printf(TEXT("##### Test %d — `%s`\n\n"), TestIdx, *EscTbl(Test->GetClass()->GetName()));
				Md += FString::Printf(TEXT("- Class: `%s`\n\n"), *EscTbl(Test->GetClass()->GetPathName()));
				const int32 N = RenderUObjectPropertiesTable(Md, Test);
				if (N == 0)
				{
					Md += TEXT("_(test declares no exposed UPROPERTYs)_\n\n");
				}
			}
		}

		return Md;
	}
}

namespace BlueprintExporter::DeepDump
{
	FString RenderEnvQueryMarkdown(UObject* EQSObject)
	{
		UEnvQuery* EQS = Cast<UEnvQuery>(EQSObject);
		if (!EQS)
		{
			return RenderOutOfScopeNotice(
				EQSObject ? EQSObject->GetName() : FString(TEXT("(null)")),
				EQSObject ? EQSObject->GetPathName() : FString(),
				TEXT("not UEnvQuery"));
		}
		return DoRenderEnvQuery(EQS);
	}
}
