// Copyright 10 Chambers. All Rights Reserved.

#include "TextExport/SmartObjectDefinitionDeepRenderer.h"
#include "TextExport/DeepDumpRenderer.h"
#include "TextExport/DeepRenderShared.h"

#include "UObject/Object.h"
#include "UObject/UnrealType.h"
#include "UObject/Class.h"

#if WITH_SMARTOBJECTS_SUPPORT
#include "SmartObjectDefinition.h"
#include "SmartObjectTypes.h"
#include "GameplayTagContainer.h"
#include "WorldConditionQuery.h"
#include "StructUtils/InstancedStruct.h"
#endif

namespace
{
	using BlueprintExporter::DeepRender::EscTbl;
	using BlueprintExporter::DeepRender::RenderUObjectPropertiesTable;
	using BlueprintExporter::DeepRender::RenderStructFieldsTable;

#if WITH_SMARTOBJECTS_SUPPORT

	// Pull a `TArray<TObjectPtr<UObject>>` field via reflection (same pattern
	// the Tier 1 SO handler uses for `DefaultBehaviorDefinitions`, but returns
	// the live UObject pointers, not just paths, so we can reflect each one).
	TArray<UObject*> ReadObjectArrayLive(const UObject* Owner, const TCHAR* PropertyName)
	{
		TArray<UObject*> Out;
		if (!Owner)
		{
			return Out;
		}
		FArrayProperty* ArrProp = FindFProperty<FArrayProperty>(Owner->GetClass(), PropertyName);
		if (!ArrProp)
		{
			return Out;
		}
		FObjectProperty* Inner = CastField<FObjectProperty>(ArrProp->Inner);
		if (!Inner)
		{
			return Out;
		}
		FScriptArrayHelper Helper(ArrProp, ArrProp->ContainerPtrToValuePtr<void>(Owner));
		Out.Reserve(Helper.Num());
		for (int32 i = 0; i < Helper.Num(); ++i)
		{
			UObject* Obj = Inner->GetObjectPropertyValue(Helper.GetRawPtr(i));
			Out.Add(Obj);
		}
		return Out;
	}

	void RenderBehaviorDefinitionBlock(FString& Md, int32 Index, UObject* Behavior, const TCHAR* Heading)
	{
		Md += FString::Printf(TEXT("%s Behavior %d\n\n"), Heading, Index);
		if (!Behavior)
		{
			Md += TEXT("- **Broken reference**: behavior slot held a null UObject pointer at export time.\n\n");
			return;
		}
		Md += FString::Printf(TEXT("- Path: `%s`\n"), *EscTbl(Behavior->GetPathName()));
		Md += FString::Printf(TEXT("- Class: `%s`\n\n"), *EscTbl(Behavior->GetClass()->GetPathName()));
		const int32 N = RenderUObjectPropertiesTable(Md, Behavior);
		if (N == 0)
		{
			Md += TEXT("_(no UPROPERTYs to render — behavior class declares no exposed fields)_\n\n");
		}
	}

	void RenderDefinitionDataBlock(FString& Md, int32 Index, const FSmartObjectDefinitionDataProxy& Proxy, const TCHAR* Heading)
	{
		const UScriptStruct* Type = Proxy.Data.GetScriptStruct();
		Md += FString::Printf(TEXT("%s Definition Data %d\n\n"), Heading, Index);
		if (!Type)
		{
			Md += TEXT("- _Unset_ (no struct type bound to this entry).\n\n");
			return;
		}
		Md += FString::Printf(TEXT("- Type: `%s`\n\n"), *EscTbl(Type->GetPathName()));
		const int32 N = RenderStructFieldsTable(Md, Type, Proxy.Data.GetMemory());
		if (N == 0)
		{
			Md += TEXT("_(struct declares no fields, or all values are at default)_\n\n");
		}
	}

	FString DoRenderSmartObjectDefinition(USmartObjectDefinition* Def)
	{
		FString Md;
		Md.Reserve(8 * 1024);

		Md += FString::Printf(TEXT("# %s — Deep Dump (Tier 2)\n\n"), *Def->GetName());
		Md += TEXT("> Generated by `DeepDump` for a SmartObjectDefinition asset. Adds full per-behavior-definition UPROPERTY tables and per-slot `FInstancedStruct` `DefinitionData` field values that the Tier 1 typed handler captures only as paths or type names. The single most load-bearing thing this exposes is the `StateTreeReference` on each `UGameplayInteractionSmartObjectBehaviorDefinition` — the link from the SO definition to the StateTree that runs the interaction.\n\n");

		// ---- Identity ----
		Md += TEXT("## Identity\n\n");
		Md += TEXT("| Field | Value |\n|---|---|\n");
		Md += FString::Printf(TEXT("| Asset path | `%s` |\n"), *EscTbl(Def->GetPathName()));
		Md += FString::Printf(TEXT("| Asset name | `%s` |\n"), *EscTbl(Def->GetName()));
		Md += TEXT("| Asset type | `SmartObjectDefinition` |\n");
		UClass* Cls = Def->GetClass();
		UClass* ParentCls = Cls ? Cls->GetSuperClass() : nullptr;
		if (ParentCls)
		{
			Md += FString::Printf(TEXT("| Parent class | `%s` |\n"), *EscTbl(ParentCls->GetPathName()));
		}
		const TSubclassOf<USmartObjectWorldConditionSchema>& SchemaClass = Def->GetWorldConditionSchemaClass();
		if (SchemaClass.Get())
		{
			Md += FString::Printf(TEXT("| World condition schema | `%s` |\n"), *EscTbl(SchemaClass->GetPathName()));
		}
		TConstArrayView<FSmartObjectSlotDefinition> SlotView = Def->GetSlots();
		Md += FString::Printf(TEXT("| Slots | **%d** |\n"), SlotView.Num());
		Md += TEXT("\n");

		// ---- Default Behavior Definitions (full property tables) ----
		const TArray<UObject*> DefaultBehaviors = ReadObjectArrayLive(Def, TEXT("DefaultBehaviorDefinitions"));
		Md += FString::Printf(TEXT("## Default Behavior Definitions (%d)\n\n"), DefaultBehaviors.Num());
		if (DefaultBehaviors.Num() == 0)
		{
			Md += TEXT("_No default behavior definitions — slots must supply their own._\n\n");
		}
		else
		{
			for (int32 i = 0; i < DefaultBehaviors.Num(); ++i)
			{
				RenderBehaviorDefinitionBlock(Md, i, DefaultBehaviors[i], TEXT("###"));
			}
		}

		// ---- Slots (full content per slot) ----
		Md += FString::Printf(TEXT("## Slots (%d)\n\n"), SlotView.Num());
		if (SlotView.Num() == 0)
		{
			Md += TEXT("_No slots._\n\n");
			return Md;
		}

		for (int32 i = 0; i < SlotView.Num(); ++i)
		{
			const FSmartObjectSlotDefinition& S = SlotView[i];
			FString SlotName;
#if WITH_EDITORONLY_DATA
			SlotName = S.Name.ToString();
#endif
			const FString Header = SlotName.IsEmpty()
				? FString::Printf(TEXT("Slot %d"), i)
				: FString::Printf(TEXT("Slot %d — `%s`"), i, *EscTbl(SlotName));
			Md += FString::Printf(TEXT("### %s\n\n"), *Header);

			Md += TEXT("| Field | Value |\n|---|---|\n");
			Md += FString::Printf(TEXT("| Offset | (%.2f, %.2f, %.2f) |\n"),
				S.Offset.X, S.Offset.Y, S.Offset.Z);
			Md += FString::Printf(TEXT("| Rotation | (P=%.2f, Y=%.2f, R=%.2f) |\n"),
				S.Rotation.Pitch, S.Rotation.Yaw, S.Rotation.Roll);
			Md += FString::Printf(TEXT("| Enabled | %s |\n"), S.bEnabled ? TEXT("yes") : TEXT("no"));
			Md += FString::Printf(TEXT("| Selection preconditions | %s |\n"),
				S.SelectionPreconditions.IsValid() ? TEXT("set") : TEXT("_unset_"));
			Md += FString::Printf(TEXT("| User tag filter | %s |\n"),
				S.UserTagFilter.IsEmpty() ? TEXT("_empty_") : TEXT("set"));
			Md += TEXT("\n");

			if (S.BehaviorDefinitions.Num() > 0)
			{
				Md += FString::Printf(TEXT("#### Behavior Definitions (%d)\n\n"), S.BehaviorDefinitions.Num());
				for (int32 j = 0; j < S.BehaviorDefinitions.Num(); ++j)
				{
					RenderBehaviorDefinitionBlock(Md, j, S.BehaviorDefinitions[j], TEXT("#####"));
				}
			}

			if (S.DefinitionData.Num() > 0)
			{
				Md += FString::Printf(TEXT("#### Definition Data (%d)\n\n"), S.DefinitionData.Num());
				for (int32 j = 0; j < S.DefinitionData.Num(); ++j)
				{
					RenderDefinitionDataBlock(Md, j, S.DefinitionData[j], TEXT("#####"));
				}
			}
		}

		return Md;
	}

#endif // WITH_SMARTOBJECTS_SUPPORT
}

namespace BlueprintExporter::DeepDump
{
	FString RenderSmartObjectDefinitionMarkdown(UObject* DefObject)
	{
#if WITH_SMARTOBJECTS_SUPPORT
		USmartObjectDefinition* Def = Cast<USmartObjectDefinition>(DefObject);
		if (!Def)
		{
			// Fall through to the standard out-of-scope notice — preserves the
			// sibling-pattern uniformity for callers that always emit a
			// `<Asset>.deep.md` regardless of whether SO Tier 2 succeeded.
			return RenderOutOfScopeNotice(
				DefObject ? DefObject->GetName() : FString(TEXT("(null)")),
				DefObject ? DefObject->GetPathName() : FString(),
				TEXT("not USmartObjectDefinition"));
		}
		return DoRenderSmartObjectDefinition(Def);
#else
		return RenderOutOfScopeNotice(
			DefObject ? DefObject->GetName() : FString(TEXT("(null)")),
			DefObject ? DefObject->GetPathName() : FString(),
			TEXT("SmartObjectDefinition (build without WITH_SMARTOBJECTS_SUPPORT)"));
#endif
	}
}
