// Copyright 10 Chambers. All Rights Reserved.

#include "TextExport/ChooserTableDeepRenderer.h"
#include "TextExport/DeepDumpRenderer.h"
#include "TextExport/DeepRenderShared.h"

#include "UObject/Object.h"
#include "UObject/UnrealType.h"
#include "UObject/Class.h"

#if WITH_CHOOSER_SUPPORT
#include "Chooser.h"
#include "IChooserColumn.h"
#include "StructUtils/InstancedStruct.h"
#endif

namespace
{
	using BlueprintExporter::DeepRender::EscTbl;
	using BlueprintExporter::DeepRender::RenderStructFieldsTable;

#if WITH_CHOOSER_SUPPORT

	// Render one FInstancedStruct block: heading + type identity + full field
	// table. `Heading` is the Markdown heading prefix (### / #### / etc.) so
	// callers can nest properly.
	void RenderInstancedStructBlock(
		FString& Md,
		const FInstancedStruct& IS,
		const TCHAR* Heading,
		const FString& Title)
	{
		Md += FString::Printf(TEXT("%s %s\n\n"), Heading, *Title);

		const UScriptStruct* Type = IS.GetScriptStruct();
		if (!Type)
		{
			Md += TEXT("- _Unset_ (no struct type bound to this entry).\n\n");
			return;
		}
		Md += FString::Printf(TEXT("- Type: `%s`\n\n"), *EscTbl(Type->GetPathName()));

		const int32 N = RenderStructFieldsTable(Md, Type, IS.GetMemory());
		if (N == 0)
		{
			Md += TEXT("_(struct declares no fields, or all values are at default)_\n\n");
		}
	}

	// Result-type enum → human label, matching the Tier 1 renderer's mapping.
	const TCHAR* ResultTypeLabel(EObjectChooserResultType T)
	{
		switch (T)
		{
		case EObjectChooserResultType::ObjectResult:    return TEXT("ObjectResult");
		case EObjectChooserResultType::ClassResult:     return TEXT("ClassResult");
		case EObjectChooserResultType::NoPrimaryResult: return TEXT("NoPrimaryResult");
		default: return TEXT("(unknown)");
		}
	}

	FString DoRenderChooserTable(UChooserTable* Chooser)
	{
		FString Md;
		Md.Reserve(16 * 1024);

		Md += FString::Printf(TEXT("# %s — Deep Dump (Tier 2)\n\n"), *Chooser->GetName());
		Md += TEXT("> Generated by `DeepDump` for a ChooserTable asset. Adds full `FInstancedStruct` field tables for every column / row / fallback / context-data entry — Tier 1 captures shape (column types, row types, has-filter/output/cost flags) but not the authored values (the enum each `FEnumColumn` reads, the per-row values that select each row, the asset each `FAssetChooser` row produces, the range each `FFloatRangeColumn` accepts). This is the Tier 2 complement.\n\n");

		// ---- Identity ----
		Md += TEXT("## Identity\n\n");
		Md += TEXT("| Field | Value |\n|---|---|\n");
		Md += FString::Printf(TEXT("| Asset path | `%s` |\n"), *EscTbl(Chooser->GetPathName()));
		Md += FString::Printf(TEXT("| Asset name | `%s` |\n"), *EscTbl(Chooser->GetName()));
		Md += TEXT("| Asset type | `ChooserTable` |\n");

		UClass* Cls = Chooser->GetClass();
		UClass* ParentCls = Cls ? Cls->GetSuperClass() : nullptr;
		if (ParentCls)
		{
			Md += FString::Printf(TEXT("| Parent class | `%s` |\n"), *EscTbl(ParentCls->GetPathName()));
		}

		Md += FString::Printf(TEXT("| Result type | `%s` |\n"), ResultTypeLabel(Chooser->ResultType));

		const FString OutputObjectTypePath = Chooser->OutputObjectType ? Chooser->OutputObjectType->GetPathName() : FString();
		Md += FString::Printf(TEXT("| Output class | %s |\n"),
			OutputObjectTypePath.IsEmpty() ? TEXT("_none_") : *FString::Printf(TEXT("`%s`"), *EscTbl(OutputObjectTypePath)));

		// Root / nested role — matches Tier 1 behaviour.
		const UChooserTable* RootChooser = Chooser->GetRootChooser();
		const bool bIsRoot = (RootChooser == Chooser) || (RootChooser == nullptr);
		const FString RootChooserPath = bIsRoot ? FString() : (RootChooser ? RootChooser->GetPathName() : FString());
		Md += FString::Printf(TEXT("| Role | %s |\n"),
			bIsRoot ? TEXT("Root chooser")
			        : *FString::Printf(TEXT("Nested under `%s`"), *EscTbl(RootChooserPath)));

		// Row source: editor assets use `ResultsStructs`; cooked assets use
		// `CookedResults`. The commandlet runs in editor mode so the editor
		// path is the one we'll hit in practice.
#if WITH_EDITORONLY_DATA
		const TArray<FInstancedStruct>& RowStructs = Chooser->ResultsStructs;
#else
		const TArray<FInstancedStruct>& RowStructs = Chooser->CookedResults;
#endif

		Md += FString::Printf(TEXT("| Columns | **%d** |\n"), Chooser->ColumnsStructs.Num());
		Md += FString::Printf(TEXT("| Rows | **%d** |\n"), RowStructs.Num());
		Md += FString::Printf(TEXT("| Context entries | %d |\n"), Chooser->ContextData.Num());
#if WITH_EDITORONLY_DATA
		Md += FString::Printf(TEXT("| Nested choosers | %d |\n"), Chooser->NestedChoosers.Num());
#endif
		Md += TEXT("\n");

		// ---- Columns ----
		// Columns are polymorphic `FChooserColumnBase` descendants
		// (FEnumColumn / FFloatRangeColumn / FBoolColumn / etc.). Each one's
		// per-row filter / output values live inside its own struct fields
		// (commonly `RowValues` arrays), so dumping the struct walks all the
		// authored data automatically via ExportTextItem_Direct.
		Md += FString::Printf(TEXT("## Columns (%d)\n\n"), Chooser->ColumnsStructs.Num());
		if (Chooser->ColumnsStructs.Num() == 0)
		{
			Md += TEXT("_No columns — chooser has no filters configured._\n\n");
		}
		else
		{
			for (int32 i = 0; i < Chooser->ColumnsStructs.Num(); ++i)
			{
				const FInstancedStruct& ColIS = Chooser->ColumnsStructs[i];
				const FString TypeName = ColIS.GetScriptStruct() ? ColIS.GetScriptStruct()->GetName() : FString(TEXT("?"));

				// Add a one-line summary of filter/output/cost flags for this
				// column on the heading line — same info Tier 1 breaks out
				// into a separate column, surfaced here as context.
				FString FlagSummary;
				if (const FChooserColumnBase* ColBase = ColIS.GetPtr<FChooserColumnBase>())
				{
					TArray<FString> Flags;
					if (ColBase->HasFilters()) { Flags.Add(TEXT("Filter")); }
					if (ColBase->HasOutputs()) { Flags.Add(TEXT("Output")); }
					if (ColBase->HasCosts())   { Flags.Add(TEXT("Cost")); }
#if WITH_EDITORONLY_DATA
					if (ColBase->bDisabled)    { Flags.Add(TEXT("Disabled")); }
#endif
					if (Flags.Num() > 0)
					{
						FlagSummary = FString::Printf(TEXT(" _(%s)_"), *FString::Join(Flags, TEXT(", ")));
					}
				}

				const FString Title = FString::Printf(TEXT("Column %d — `%s`%s"), i, *EscTbl(TypeName), *FlagSummary);
				RenderInstancedStructBlock(Md, ColIS, TEXT("###"), Title);
			}
		}

		// ---- Rows ----
		// Rows are polymorphic `FObjectChooserBase` descendants
		// (FAssetChooser pointing at a UObject, FEvaluateChooser pointing at
		// another UChooserTable, FNestedChooser pointing at an embedded one,
		// etc.). Per-row authored data — most importantly the `Asset` path on
		// FAssetChooser rows — lives inside these struct fields.
		Md += FString::Printf(TEXT("## Rows (%d)\n\n"), RowStructs.Num());
		if (RowStructs.Num() == 0)
		{
			Md += TEXT("_No rows — chooser has no results configured._\n\n");
		}
		else
		{
			for (int32 i = 0; i < RowStructs.Num(); ++i)
			{
				const FInstancedStruct& RowIS = RowStructs[i];
				const FString TypeName = RowIS.GetScriptStruct() ? RowIS.GetScriptStruct()->GetName() : FString(TEXT("?"));

				FString DisabledSuffix;
#if WITH_EDITORONLY_DATA
				if (Chooser->DisabledRows.IsValidIndex(i) && Chooser->DisabledRows[i])
				{
					DisabledSuffix = TEXT(" _(disabled)_");
				}
#endif

				const FString Title = FString::Printf(TEXT("Row %d — `%s`%s"), i, *EscTbl(TypeName), *DisabledSuffix);
				RenderInstancedStructBlock(Md, RowIS, TEXT("###"), Title);
			}
		}

		// ---- Fallback ----
		if (Chooser->FallbackResult.GetScriptStruct() != nullptr)
		{
			Md += TEXT("## Fallback\n\n");
			const FString TypeName = Chooser->FallbackResult.GetScriptStruct()->GetName();
			const FString Title = FString::Printf(TEXT("Fallback — `%s`"), *EscTbl(TypeName));
			RenderInstancedStructBlock(Md, Chooser->FallbackResult, TEXT("###"), Title);
		}
		else
		{
			Md += TEXT("## Fallback\n\n_No fallback row configured — a chooser that doesn't hit any row with a valid result will return null._\n\n");
		}

		// ---- Context data ----
		if (Chooser->ContextData.Num() > 0)
		{
			Md += FString::Printf(TEXT("## Context Data (%d)\n\n"), Chooser->ContextData.Num());
			for (int32 i = 0; i < Chooser->ContextData.Num(); ++i)
			{
				const FInstancedStruct& CtxIS = Chooser->ContextData[i];
				const FString TypeName = CtxIS.GetScriptStruct() ? CtxIS.GetScriptStruct()->GetName() : FString(TEXT("?"));
				const FString Title = FString::Printf(TEXT("Context %d — `%s`"), i, *EscTbl(TypeName));
				RenderInstancedStructBlock(Md, CtxIS, TEXT("###"), Title);
			}
		}

		// ---- Nested choosers ----
#if WITH_EDITORONLY_DATA
		if (Chooser->NestedChoosers.Num() > 0)
		{
			Md += FString::Printf(TEXT("## Nested Choosers (%d)\n\n"), Chooser->NestedChoosers.Num());
			// Sort alpha by path for determinism, same as Tier 1.
			TArray<FString> Paths;
			Paths.Reserve(Chooser->NestedChoosers.Num());
			for (const TObjectPtr<UChooserTable>& NC : Chooser->NestedChoosers)
			{
				if (NC)
				{
					Paths.Add(NC->GetPathName());
				}
			}
			Paths.Sort([](const FString& A, const FString& B)
			{
				return A.Compare(B, ESearchCase::IgnoreCase) < 0;
			});
			Md += TEXT("| # | Path |\n|---|---|\n");
			for (int32 i = 0; i < Paths.Num(); ++i)
			{
				Md += FString::Printf(TEXT("| %d | `%s` |\n"), i, *EscTbl(Paths[i]));
			}
			Md += TEXT("\n");
			Md += TEXT("_Nested choosers are embedded sub-tables; each is also a distinct `/Game/…` asset and gets its own deep dump in the sweep._\n\n");
		}
#endif

		return Md;
	}

#endif // WITH_CHOOSER_SUPPORT
}

namespace BlueprintExporter::DeepDump
{
	FString RenderChooserTableMarkdown(UObject* ChooserObject)
	{
#if WITH_CHOOSER_SUPPORT
		UChooserTable* Chooser = Cast<UChooserTable>(ChooserObject);
		if (!Chooser)
		{
			return RenderOutOfScopeNotice(
				ChooserObject ? ChooserObject->GetName() : FString(TEXT("(null)")),
				ChooserObject ? ChooserObject->GetPathName() : FString(),
				TEXT("not UChooserTable"));
		}
		return DoRenderChooserTable(Chooser);
#else
		return RenderOutOfScopeNotice(
			ChooserObject ? ChooserObject->GetName() : FString(TEXT("(null)")),
			ChooserObject ? ChooserObject->GetPathName() : FString(),
			TEXT("ChooserTable (build without WITH_CHOOSER_SUPPORT)"));
#endif
	}
}
