// Copyright 10 Chambers. All Rights Reserved.

#include "TextExport/DataTableDeepRenderer.h"
#include "TextExport/DeepDumpRenderer.h"
#include "TextExport/DeepRenderShared.h"

#include "UObject/Object.h"
#include "UObject/UnrealType.h"
#include "UObject/Class.h"
#include "Engine/DataTable.h"

namespace
{
	using BlueprintExporter::DeepRender::EscTbl;

	// Walk a UScriptStruct instance's fields (alpha-sorted by field name) and
	// render a Markdown property table against the caller-supplied memory
	// pointer. Returns row count so callers can elide the empty-row case.
	//
	// Same shape as SO's `RenderStructFieldsTable`; duplicated here to keep
	// the two renderers independent (DT doesn't need the SmartObjects header
	// dependency that SO pulls in).
	int32 RenderRowFieldsTable(FString& Md, const UScriptStruct* RowStruct, const void* RowMemory)
	{
		if (!RowStruct || !RowMemory)
		{
			return 0;
		}

		struct FRow { FString Name; FString Type; FString Value; };
		TArray<FRow> Rows;

		for (TFieldIterator<FProperty> It(RowStruct); It; ++It)
		{
			FProperty* P = *It;
			if (!P)
			{
				continue;
			}
			FRow R;
			R.Name = P->GetName();
			R.Type = P->GetCPPType();
			const void* ValuePtr = P->ContainerPtrToValuePtr<void>(RowMemory);
			P->ExportTextItem_Direct(R.Value, ValuePtr, nullptr, nullptr, PPF_None);
			Rows.Add(MoveTemp(R));
		}

		if (Rows.Num() == 0)
		{
			return 0;
		}

		Rows.Sort([](const FRow& A, const FRow& B)
		{
			return A.Name.Compare(B.Name, ESearchCase::IgnoreCase) < 0;
		});

		Md += TEXT("| Field | Type | Value |\n");
		Md += TEXT("|---|---|---|\n");
		for (const FRow& R : Rows)
		{
			const FString ValueCell = R.Value.IsEmpty()
				? FString(TEXT("—"))
				: FString::Printf(TEXT("`%s`"), *EscTbl(R.Value));
			Md += FString::Printf(TEXT("| `%s` | `%s` | %s |\n"),
				*EscTbl(R.Name), *EscTbl(R.Type), *ValueCell);
		}
		Md += TEXT("\n");
		return Rows.Num();
	}

	FString DoRenderDataTable(UDataTable* DT)
	{
		FString Md;
		Md.Reserve(8 * 1024);

		const UScriptStruct* RowStruct = DT->GetRowStruct();
		const TMap<FName, uint8*>& RowMap = DT->GetRowMap();

		Md += FString::Printf(TEXT("# %s — Deep Dump (Tier 2)\n\n"), *DT->GetName());
		Md += TEXT("> Generated by `DeepDump` for a DataTable asset. Adds per-row property tables with the authored values — Tier 1 captures schema only (row struct, column names + types, sorted row-name list) per brief §4, so the actual data each row carries (e.g. `Damage=15` / `Icon=/Game/UI/...` / `Tier=Common` on a row named `Sword_Iron`) is only readable at Tier 2.\n\n");

		// ---- Identity ----
		Md += TEXT("## Identity\n\n");
		Md += TEXT("| Field | Value |\n|---|---|\n");
		Md += FString::Printf(TEXT("| Asset path | `%s` |\n"), *EscTbl(DT->GetPathName()));
		Md += FString::Printf(TEXT("| Asset name | `%s` |\n"), *EscTbl(DT->GetName()));
		Md += TEXT("| Asset type | `DataTable` |\n");
		UClass* Cls = DT->GetClass();
		UClass* ParentCls = Cls ? Cls->GetSuperClass() : nullptr;
		if (ParentCls)
		{
			Md += FString::Printf(TEXT("| Parent class | `%s` |\n"), *EscTbl(ParentCls->GetPathName()));
		}
		Md += FString::Printf(TEXT("| Row struct | %s |\n"),
			RowStruct
				? *FString::Printf(TEXT("`%s`"), *EscTbl(RowStruct->GetPathName()))
				: TEXT("_none_"));
		Md += FString::Printf(TEXT("| Row count | **%d** |\n"), RowMap.Num());
		Md += TEXT("\n");

		// ---- Early-outs before the per-row walk ----
		if (!RowStruct)
		{
			Md += TEXT("## Rows\n\n_Row struct is unset or could not be resolved — no row values to render. Tier 1 `.md` captures the row-name list; `.meta.json` has the structured form._\n\n");
			return Md;
		}

		if (RowMap.Num() == 0)
		{
			Md += TEXT("## Rows\n\n_Empty table._\n\n");
			return Md;
		}

		// ---- Per-row property tables ----
		// Sort row names alphabetically — same ordering as the Tier 1 `.md`'s
		// "Row Names" list, so consumers can cross-reference the two files
		// positionally.
		TArray<FName> RowNames;
		RowNames.Reserve(RowMap.Num());
		for (const TPair<FName, uint8*>& It : RowMap)
		{
			RowNames.Add(It.Key);
		}
		RowNames.Sort([](const FName& A, const FName& B) { return A.LexicalLess(B); });

		Md += FString::Printf(TEXT("## Rows (%d)\n\n"), RowNames.Num());
		for (const FName& RowName : RowNames)
		{
			const uint8* const* RowPtrPtr = RowMap.Find(RowName);
			const uint8* RowMemory = RowPtrPtr ? *RowPtrPtr : nullptr;

			Md += FString::Printf(TEXT("### Row `%s`\n\n"), *EscTbl(RowName.ToString()));

			if (!RowMemory)
			{
				Md += TEXT("_(row backing buffer was null at export time — no values to render)_\n\n");
				continue;
			}

			const int32 N = RenderRowFieldsTable(Md, RowStruct, RowMemory);
			if (N == 0)
			{
				Md += TEXT("_(row struct declares no fields, or all values are at default)_\n\n");
			}
		}

		return Md;
	}
}

namespace BlueprintExporter::DeepDump
{
	FString RenderDataTableMarkdown(UObject* DTObject)
	{
		UDataTable* DT = Cast<UDataTable>(DTObject);
		if (!DT)
		{
			// Fall through to the standard out-of-scope notice — preserves the
			// sibling-pattern uniformity for callers that always emit a
			// `<Asset>.deep.md` regardless of whether DT Tier 2 succeeded.
			return RenderOutOfScopeNotice(
				DTObject ? DTObject->GetName() : FString(TEXT("(null)")),
				DTObject ? DTObject->GetPathName() : FString(),
				TEXT("not UDataTable"));
		}
		return DoRenderDataTable(DT);
	}
}
